image: jakzal/phpqa:php8.1

before_script:
    - cd symfony
    - composer install
    - php bin/console doctrine:database:create --if-not-exists
    - php bin/console doctrine:schema:update --force --no-interaction
    

cache:
    paths:
        - vendor/

stages:
    - SecurityChecker
    - CodingStandards
    - UnitTests

security-checker:
    stage: SecurityChecker
    script:
        - local-php-security-checker  --path=./composer.lock
    allow_failure: false

phpcs:
    stage: CodingStandards
    script:
        - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src
    allow_failure: false

phpstan:
    stage: CodingStandards
    script:
        - phpstan analyse ./src
    allow_failure: false

services:
  - mysql:8.0

variables:
  MYSQL_DATABASE: etu_ajessondanie
  MYSQL_ROOT_PASSWORD: 3m8MFs8q
  DATABASE_URL: mysql://ajessondanie:3m8MFs8q@mysql/etu_ajessondanie

phpunit:
  stage: test
  script:
    - php bin/console doctrine:fixtures:load --no-interaction
    - php bin/phpunit --stop-on-failure
  allow_failure: false