nelmio_api_doc:
    documentation:
        info:
            title: API the-bookshelf
            description: This is the API documentation for the-bookshelf.
            version: 1.0.0
        components:
            schemas:
                Login:
                    type: "object"
                    properties:
                        email:
                            type: "string"
                            description: "Email of the user"
                            example: "Nathan@gmail.com"
                        password:
                            type: "string"
                            description: "Password of the user"
                            example: "Nathan33"
                Logout:
                    type: "object"
                    properties:
                        token:
                            type: "string"
                            description: "token of the user"
                            example: "CxFQHyVyI5O0fAmv0oBH1J/6vHcx0I95oiDjCyHSces"
                Follow(ed): 
                    type: "integer"
                    description: "id of the user"   
                    example: "1"
                Books:
                    type: "string"
                    description: "cherch by author"
                    example: "Emile Zola"   

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
